## Gateway image settings
#
clusterSizeType: mid
image:
  imagePullSecrets:
    - name: secupi-registry
  repository: registry.gitlab.com/secupi/secupi-distribution

## SecuPi Gateway related configuration
#

gateway:
  preSharedCertName: null # must replace null with real pre-shared-cert-name
  externalIngressName: null # must replace null with real external-ingress-name
  env:
    GATEWAY_SERVER_HOST: null # must replace with real value e.g 10.0.0.1
    SECUPI_BOOT_URL: null # must replace with real value e.g https://XXX.YYY.ZZZ.AAA/api/boot/download/XXXXXXXX/secupi-boot-XXXXXX.jar
    EXTRA_OPTS: "-XX:+ExitOnOutOfMemoryError -Dsecupi.agent.abortStartupOnFailure=true -XX:MaxRAMPercentage=75.0"
