services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-private-01
    restart: unless-stopped
    volumes:
      - /data/ipfs-private-01:/data/ipfs
      - ./start-ipfs.sh:/start-ipfs.sh
    networks:
      private_network:
        ipv4_address: 172.21.0.10
    ports:
      - "4001:4001"   # P2P swarm (internal cluster communication)
    entrypoint: ["/bin/sh", "/start-ipfs.sh"]
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  ipfs-cluster:
    build:
      context: .
      dockerfile: Dockerfile.cluster
    container_name: ipfs-cluster-private-01
    restart: unless-stopped
    environment:
      - CLUSTER_IPFSHTTP_NODEMULTIADDRESS=/dns4/ipfs/tcp/5001
      - CLUSTER_CRDT_TRUSTALLPEERS=true
      - CLUSTER_CRDT_DATACENTER=private-cluster-01
<<<<<<< HEAD
      - CLUSTER_CRDT_CLUSTERNAME=bongaquino-private-ipfs-cluster
=======
      - CLUSTER_CRDT_CLUSTERNAME=bongaquino-private-ipfs-cluster
>>>>>>> ff1a2945f8bd7c03b52b06fcba179354b2b893ff
      - CLUSTER_BOOTSTRAP_NODE=true
      - CLUSTER_SECRET=a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      - CLUSTER_PEERNAME=private-cluster-01
      - CLUSTER_MONITORPINGINTERVAL=15s
      - CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS=/ip4/0.0.0.0/tcp/9094
      - CLUSTER_RESTAPI_HTTPANNOUNCEMULTIADDRESS=/ip4/172.21.0.10/tcp/9094
      - CLUSTER_SWARM_LISTENMULTIADDRESS=/ip4/0.0.0.0/tcp/9096
      - CLUSTER_SWARM_ANNOUNCE=/ip4/172.21.0.10/tcp/9096
      - CLUSTER_DEBUG=false
    networks:
      private_network:
        ipv4_address: 172.21.0.10
    volumes:
      - /data/ipfs-cluster-private-01:/data/ipfs-cluster
      - ./service.json:/data/ipfs-cluster/service.json
    depends_on:
      ipfs:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "ipfs-cluster-ctl", "id"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

networks:
  private_network:
    external: true
    name: private-cluster-project_private_network 