apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
  labels:
    app: postgres-client
spec:
  containers:
  - name: postgres-client
    image: postgres:13
    command: ['sleep', '3600']
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: password
