apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    # SSL Configuration
    ssl = on
    ssl_cert_file = '/var/lib/postgresql/ssl/secupi.crt'
    ssl_key_file = '/var/lib/postgresql/ssl/secupi.key'
    ssl_ca_file = '/var/lib/postgresql/ssl/secupi.crt'
    ssl_prefer_server_ciphers = on
    
    # Connection settings
    listen_addresses = '*'
    port = 5432
    max_connections = 100
    
    # Logging
    log_statement = 'all'
    log_connections = on
    log_disconnections = on
