name: 'Terraform Staging'

on:
  push:
    branches:
      - staging
    paths:
      - 'modules/app_platform/staging/**'
      - '.github/workflows/staging-terraform.yml'
  pull_request:
    branches:
      - staging
    paths:
      - 'modules/app_platform/staging/**'
      - '.github/workflows/staging-terraform.yml'

permissions:
  contents: read
  pull-requests: write

env:
  TF_WORKSPACE: staging
  TF_CLOUD_ORGANIZATION: bongaquino-tech

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: 
      name: 'staging-env'
      url: https://cloud.digitalocean.com/apps

    defaults:
      run:
        working-directory: modules/app_platform/staging

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      continue-on-error: true

    - name: Update Pull Request
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.name,
            body: output
          })

    - name: Terraform Apply
      if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }} 