services:
  haproxy:
    image: haproxy:2.8-alpine
    container_name: haproxy-public
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"  # HAProxy stats
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./ssl:/etc/ssl/certs:ro
      - ./logs:/var/log/haproxy
    networks:
      - public_network
      - private_network
    environment:
      - HAPROXY_USER=admin
      - HAPROXY_PASSWORD=secure123!
    depends_on:
      - certbot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot
    container_name: certbot-haproxy
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
    networks:
      - public_network

  nginx-ssl-companion:
    image: nginx:alpine
    container_name: nginx-ssl
    ports:
      - "8080:80"
    volumes:
      - ./certbot-www:/var/www/certbot:ro
      - ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - public_network

networks:
  public_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  private_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24 