apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: learning  # This matches our pod's label
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP  # Internal access only
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  selector:
    app: learning
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort  # External access
