apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  # postgres
  POSTGRES_USER: cG9zdGdyZXM=
  # strongpassword123
  POSTGRES_PASSWORD: c3Ryb25ncGFzc3dvcmQxMjM=
  # postgresdb
  POSTGRES_DB: cG9zdGdyZXNkYg==
